moony:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    wheel_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: wheel_1_joint
      pid: {p: 15.0, i: 15.0, d: 5.0}

    # wheel_2_joint_position_controller:
    #   type: effort_controllers/JointPositionController
    #   joint: wheel_2_joint
    #   pid: {p: 1.0, i: 1.0, d: 0.0}

    # wheel_3_joint_position_controller:
    #   type: effort_controllers/JointPositionController
    #   joint: wheel_3_joint
    #   pid: {p: 1.0, i: 1.0, d: 0.0}

    # wheel_4_joint_position_controller:
    #   type: effort_controllers/JointPositionController
    #   joint: wheel_4_joint
    #   pid: {p: 1.0, i: 1.0, d: 0.0}
# To add more just add them here as the first one