moony:
    # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  gazebo_ros_control:
    pid_gains:
      wheel_1_joint:
        p: 100
        i: 10
        d: 0.1
      wheel_2_joint:
        p: 100
        i: 10
        d: 0.1
      wheel_3_joint:
        p: 100
        i: 10
        d: 0.1
      wheel_4_joint:
        p: 100
        i: 10
        d: 0.1
  