<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="moony">

<gazebo>
  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
    <updateRate>100.0</updateRate>
    <robotNamespace>/moony</robotNamespace>
    <leftFrontJoint>wheel_1_joint</leftFrontJoint>
    <rightFrontJoint>wheel_3_joint</rightFrontJoint>
    <leftRearJoint>wheel_2_joint</leftRearJoint>
    <rightRearJoint>wheel_4_joint</rightRearJoint>
    <wheelSeparation>${wheel_y * 2}</wheelSeparation>
    <wheelDiameter>${wheel_collision_radius}</wheelDiameter>
    <robotBaseFrame>base_footprint</robotBaseFrame>
    <!-- should this be base_footprint? -->
    <topicName>/moony/cmd_vel</topicName>
    <commandTopic>/moony/cmd_vel</commandTopic>
    <torque>20</torque>
    <odometryTopic>skid_drive</odometryTopic>
    <odometryFrame>skid_drive</odometryFrame>
    <broadcastTF>false</broadcastTF>
    <covariance_x>0.000100</covariance_x>
    <covariance_y>0.000100</covariance_y>
    <covariance_yaw>0.010000</covariance_yaw>
    
    
  </plugin>
</gazebo>

</robot>