# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (my_robot_control.launch).

# BEWARE - having controllers in namespace as cascading side effects
#   I could not get it to work with a namespace
# moony:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
# source: http://wiki.ros.org/ros_control
# recieves a position input, sends an effort output
leftLinearActuator_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_linear_actuator_joint
  pid: {p: 0.125, i: 0.001, d: 0.025}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
rightLinearActuator_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_linear_actuator_joint
  pid: {p: 0.125, i: 0.001, d: 0.025}
  #pid: {p: 50.0, i: 0.1, d: 0.0}